### PR TITLE
Added Dark Mode support

### PR DESCRIPTION
**Pull request by lapstjup**
This is a proposed Dark Mode implementation for #17.

**Changes:-**
1) Used useContext to have a global theme.
2) Persistence is happening through localStorage
3) The index.css file has appropriate .dark classes for elements.

Note - The gif is kinda laggy (big size :p) but that's not how the true behaviour is.

react-builder-dark-mode-PR

### CODE REVIEW

**Review by amanjagdev — CHANGES_REQUESTED** [review]
@lapstjup Your work is amazing and I really liked your "reactive" approach and how you handled the things by using context (a more modular approach).
But there are a few things that are kinda problematic.
Your colours of dark mode don't align very well with the current ongoing theme and they are kind of a bit saturated.

If you can just improve the colour scheme for this and use better colours which doesn't saturate much and looks good to eye then this would be perfect and I can then merge your PR.
PS: you can take inspiration for colours from other PRs which didn't make it due to some other issues.

**Comment by lapstjup** [comment]
Cool @amanjagdev let me work on the color scheme and I will push the respective changes

**Comment by amanjagdev** [comment]
> Thanks @amanjagdev 😄 . Let me work on the color scheme and I will push the respective changes.

Great :)

**Comment by lapstjup** [comment]
Hey @amanjagdev I have pushed the latest changes with updated color scheme. Also made a custom useTheme hook for better abstraction.

**Comment by amanjagdev** [comment]
@lapstjup Now it looks great.
Great work :)

PS: Star the project if you liked it

**Pull request merged**
