### PR TITLE
Github Repo Buttons Added

### PR DESCRIPTION
**Pull request by harshalkaigaonkar**

### CODE REVIEW

**Comment by amanjagdev** [comment]
This looks good enough actually there are some problems, 
The code formatting that you must be using is different from the one used in the project and it's adding many lines in the commit and I can not see the difference clearly regarding the additions you made.
Can you revert back that formatting to the original one and stick to that only while adding those buttons.

**Comment by amanjagdev** [comment]
image
Moreover, I feel they should be placed in the same horizontal level as of the "Setup your app" Text

**Comment by harshalkaigaonkar** [comment]
> image
> Moreover, I feel they should be placed in the same horizontal level as of the "Setup your app" Text

sure.

**Comment by harshalkaigaonkar** [comment]
> This looks good enough actually there are some problems,
> The code formatting that you must be using is different from the one used in the project and it's adding many lines in the commit and I can not see the difference clearly regarding the additions you made.
> Can you revert back that formatting to the original one and stick to that only while adding those buttons.

Do i have to make new Component for buttons?

**Comment by amanjagdev** [comment]
> > This looks good enough actually there are some problems,
> > The code formatting that you must be using is different from the one used in the project and it's adding many lines in the commit and I can not see the difference clearly regarding the additions you made.
> > Can you revert back that formatting to the original one and stick to that only while adding those buttons.
> 
> Do i have to make new Component for buttons?

Nothing like that.. your approach is correct just center them horizontally and I was saying that due to your "formatter" that you must be using is different from the one used in the project so if you can use the original formatting of text while doing the changes.

**Comment by harshalkaigaonkar** [comment]
i've made the changes so should make a new PR?

**Comment by amanjagdev** [comment]
> i've made the changes so should make a new PR?

Ya that would be good ... I will be closing this one then

**Pull request closed without merging**
