### PR TITLE
Made web app responsive to mobile

### PR DESCRIPTION
**Pull request by vj-abishek**
@amanjagdev Things I did in this PR

- [x] Made web app fully responsive
- [x] InfoPane also reacts to the screen size

### CODE REVIEW

**Comment by vj-abishek** [comment]
#21

**Comment by vj-abishek** [comment]
https://github.com/amanjagdev/react-builder/pull/22.patch

https://github.com/amanjagdev/react-builder/pull/22.diff

**Comment by vj-abishek** [comment]
@amanjagdev Made the website fully Responsive

**Comment by vj-abishek** [comment]
#21 My new implementation

**Comment by vj-abishek** [comment]
@amanjagdev here is the preview URL https://react-builder-guk2zisi3.vercel.app/

**Comment by amanjagdev** [comment]
@vj-abishek I must say you did an awesome job implementing this but there are a few things that are rather better in other PRs.
Other PRs have a more modular approach for the stuff.
Despite your hard work, unfortunately, I can not merge your PR.

I would suggest you take a look at other issues :)

**Pull request closed without merging**
